package frontend;

import backend.TrainerRole;
import javax.swing.JOptionPane;
import java.lang.RuntimeException;

public class AddClassWindow extends javax.swing.JFrame {

    private TrainerRoleWindow prevWindow;
    private TrainerRole trainer;

    public AddClassWindow(TrainerRoleWindow prevWindow, TrainerRole trainer) {
        initComponents();
        this.prevWindow = prevWindow;
        this.trainer = trainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputClassName = new javax.swing.JTextField();
        javax.swing.JLabel lblName = new javax.swing.JLabel();
        javax.swing.JLabel lblId = new javax.swing.JLabel();
        inputClassId = new javax.swing.JTextField();
        inputDuration = new javax.swing.JTextField();
        javax.swing.JLabel lblSpeciality = new javax.swing.JLabel();
        javax.swing.JLabel lblEmail = new javax.swing.JLabel();
        inputTrainerId = new javax.swing.JTextField();
        inputMaxParticipants = new javax.swing.JTextField();
        javax.swing.JLabel lblPhoneNumber = new javax.swing.JLabel();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Class");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(474, 469));
        setResizable(false);
        setSize(new java.awt.Dimension(474, 469));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        inputClassName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputClassName.setMaximumSize(new java.awt.Dimension(56, 18));
        inputClassName.setMinimumSize(new java.awt.Dimension(56, 18));
        inputClassName.setPreferredSize(new java.awt.Dimension(56, 18));
        inputClassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputClassNameActionPerformed(evt);
            }
        });

        lblName.setBackground(new java.awt.Color(102, 255, 153));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Class Name");
        lblName.setToolTipText("");
        lblName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblName.setOpaque(true);

        lblId.setBackground(new java.awt.Color(102, 255, 153));
        lblId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("Class Id");
        lblId.setToolTipText("");
        lblId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblId.setMaximumSize(new java.awt.Dimension(56, 18));
        lblId.setMinimumSize(new java.awt.Dimension(56, 18));
        lblId.setOpaque(true);
        lblId.setPreferredSize(new java.awt.Dimension(56, 18));

        inputClassId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputClassId.setMaximumSize(new java.awt.Dimension(56, 18));
        inputClassId.setMinimumSize(new java.awt.Dimension(56, 18));
        inputClassId.setPreferredSize(new java.awt.Dimension(56, 18));
        inputClassId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputClassIdActionPerformed(evt);
            }
        });

        inputDuration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputDuration.setMaximumSize(new java.awt.Dimension(56, 18));
        inputDuration.setMinimumSize(new java.awt.Dimension(56, 18));
        inputDuration.setPreferredSize(new java.awt.Dimension(56, 18));
        inputDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDurationActionPerformed(evt);
            }
        });

        lblSpeciality.setBackground(new java.awt.Color(102, 255, 153));
        lblSpeciality.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSpeciality.setForeground(new java.awt.Color(0, 0, 0));
        lblSpeciality.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpeciality.setText("Duration");
        lblSpeciality.setToolTipText("");
        lblSpeciality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSpeciality.setOpaque(true);

        lblEmail.setBackground(new java.awt.Color(102, 255, 153));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Trainer Id");
        lblEmail.setToolTipText("");
        lblEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEmail.setMaximumSize(new java.awt.Dimension(56, 18));
        lblEmail.setMinimumSize(new java.awt.Dimension(56, 18));
        lblEmail.setOpaque(true);
        lblEmail.setPreferredSize(new java.awt.Dimension(56, 18));

        inputTrainerId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputTrainerId.setMaximumSize(new java.awt.Dimension(56, 18));
        inputTrainerId.setMinimumSize(new java.awt.Dimension(56, 18));
        inputTrainerId.setPreferredSize(new java.awt.Dimension(56, 18));
        inputTrainerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTrainerIdActionPerformed(evt);
            }
        });

        inputMaxParticipants.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputMaxParticipants.setMaximumSize(new java.awt.Dimension(56, 18));
        inputMaxParticipants.setMinimumSize(new java.awt.Dimension(56, 18));
        inputMaxParticipants.setPreferredSize(new java.awt.Dimension(56, 18));
        inputMaxParticipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMaxParticipantsActionPerformed(evt);
            }
        });

        lblPhoneNumber.setBackground(new java.awt.Color(102, 255, 153));
        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(0, 0, 0));
        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoneNumber.setText("Max Participants");
        lblPhoneNumber.setToolTipText("");
        lblPhoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPhoneNumber.setOpaque(true);

        Add.setBackground(new java.awt.Color(0, 0, 0));
        Add.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(204, 204, 204));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputClassName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputMaxParticipants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputTrainerId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputClassId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblEmail, lblId, lblName, lblPhoneNumber, lblSpeciality});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputClassId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTrainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMaxParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {inputClassId, inputClassName, inputDuration, inputMaxParticipants, inputTrainerId, lblEmail, lblId, lblName, lblPhoneNumber, lblSpeciality});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputClassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputClassNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputClassNameActionPerformed

    private void inputClassIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputClassIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputClassIdActionPerformed

    private void inputDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDurationActionPerformed

    private void inputTrainerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTrainerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTrainerIdActionPerformed

    private void inputMaxParticipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMaxParticipantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMaxParticipantsActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        String classID = inputClassId.getText().strip();
        String className = inputClassName.getText().strip();
        String trainerID = inputTrainerId.getText().strip();
        String duration = inputDuration.getText().strip();
        String maxParticipants = inputMaxParticipants.getText().strip();

        if (classID.equals("") || className.equals("") || trainerID.equals("") || duration.equals("") || maxParticipants.equals(""))
            JOptionPane.showMessageDialog(this, "Some fields are Empty!", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                Integer.parseInt(duration);
                Integer.parseInt(maxParticipants);
                try {
                    trainer.addClass(classID, className, trainerID, Integer.parseInt(duration), Integer.parseInt(maxParticipants));
                    JOptionPane.showMessageDialog(this, "The Class with Id = " + classID + " has been successfully added");
                    this.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "You should enter a valid number in Duration and Max Participants fields", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AddActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prevWindow.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField inputClassId;
    private javax.swing.JTextField inputClassName;
    private javax.swing.JTextField inputDuration;
    private javax.swing.JTextField inputMaxParticipants;
    private javax.swing.JTextField inputTrainerId;
    // End of variables declaration//GEN-END:variables
}
