package frontend;

import backend.AdminRole;

public class AdminRoleWindow extends javax.swing.JFrame {

    private AdminRole admin;
    
    public AdminRoleWindow() {
        initComponents();
        admin = new AdminRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewTrainers = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        RemoveTrainer = new javax.swing.JButton();
        AddTrainer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Role");
        setMinimumSize(new java.awt.Dimension(400, 328));

        ViewTrainers.setBackground(new java.awt.Color(0, 0, 0));
        ViewTrainers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewTrainers.setForeground(new java.awt.Color(204, 204, 204));
        ViewTrainers.setText("View Trainers");
        ViewTrainers.setToolTipText("");
        ViewTrainers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTrainersActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(204, 204, 204));
        Logout.setText("Logout");
        Logout.setToolTipText("");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        RemoveTrainer.setBackground(new java.awt.Color(0, 0, 0));
        RemoveTrainer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RemoveTrainer.setForeground(new java.awt.Color(204, 204, 204));
        RemoveTrainer.setText("Remove Trainer");
        RemoveTrainer.setToolTipText("");
        RemoveTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTrainerActionPerformed(evt);
            }
        });

        AddTrainer.setBackground(new java.awt.Color(0, 0, 0));
        AddTrainer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddTrainer.setForeground(new java.awt.Color(204, 204, 204));
        AddTrainer.setText("Add Trainer");
        AddTrainer.setToolTipText("");
        AddTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTrainerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddTrainer, RemoveTrainer, ViewTrainers});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(AddTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RemoveTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTrainersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTrainersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTrainersActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        admin.logout();
        this.dispose();
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void RemoveTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveTrainerActionPerformed

    private void AddTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTrainerActionPerformed
        new AddTrainerWindow(this, admin).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_AddTrainerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTrainer;
    private javax.swing.JButton Logout;
    private javax.swing.JButton RemoveTrainer;
    private javax.swing.JButton ViewTrainers;
    // End of variables declaration//GEN-END:variables
}
