/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.TrainerRole;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class CancelRegistrationWindow extends javax.swing.JFrame {

    private TrainerRoleWindow prevWindow;
    private TrainerRole trainer;

    public CancelRegistrationWindow(TrainerRoleWindow prevWindow, TrainerRole trainer) {
        initComponents();
        this.prevWindow = prevWindow;
        this.trainer = trainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel lblTrainerId = new javax.swing.JLabel();
        inputMemberId = new javax.swing.JTextField();
        CancelRegistration = new javax.swing.JButton();
        javax.swing.JLabel lblTrainerId1 = new javax.swing.JLabel();
        inputClassId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cancel Registration");
        setMinimumSize(new java.awt.Dimension(480, 130));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblTrainerId.setBackground(new java.awt.Color(102, 255, 153));
        lblTrainerId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTrainerId.setForeground(new java.awt.Color(0, 0, 0));
        lblTrainerId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrainerId.setText("Member Id");
        lblTrainerId.setToolTipText("");
        lblTrainerId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTrainerId.setOpaque(true);

        inputMemberId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMemberIdActionPerformed(evt);
            }
        });

        CancelRegistration.setBackground(new java.awt.Color(0, 0, 0));
        CancelRegistration.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CancelRegistration.setForeground(new java.awt.Color(204, 204, 204));
        CancelRegistration.setText("Cancel Registration");
        CancelRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelRegistrationActionPerformed(evt);
            }
        });

        lblTrainerId1.setBackground(new java.awt.Color(102, 255, 153));
        lblTrainerId1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTrainerId1.setForeground(new java.awt.Color(0, 0, 0));
        lblTrainerId1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrainerId1.setText("Class Id");
        lblTrainerId1.setToolTipText("");
        lblTrainerId1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTrainerId1.setOpaque(true);

        inputClassId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputClassId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputClassIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTrainerId1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(inputClassId, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTrainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(inputMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelRegistration)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrainerId1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputClassId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelRegistrationActionPerformed
        String memberId = inputMemberId.getText().strip();
        String classId = inputClassId.getText().strip();
        if(!(memberId.equals("") || classId.equals(""))) {
            try {
                trainer.cancelRegistration(memberId, classId);
                JOptionPane.showMessageDialog(this, "The Member with Id = " + memberId + " has been unregistered from class " + classId);
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Some fields are Empty!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_CancelRegistrationActionPerformed

    private void inputMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMemberIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMemberIdActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       prevWindow.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void inputClassIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputClassIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputClassIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelRegistration;
    private javax.swing.JTextField inputClassId;
    private javax.swing.JTextField inputMemberId;
    // End of variables declaration//GEN-END:variables
}
