/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.AdminRole;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class RemoveTrainerWindow extends javax.swing.JFrame {

    private AdminRoleWindow prevWindow;
    private AdminRole admin;

    public RemoveTrainerWindow(AdminRoleWindow prevWindow, AdminRole admin) {
        initComponents();
        this.prevWindow = prevWindow;
        this.admin = admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel lblTrainerId = new javax.swing.JLabel();
        inputTrainerId = new javax.swing.JTextField();
        Remove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove Trainer");
        setMinimumSize(new java.awt.Dimension(480, 130));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblTrainerId.setBackground(new java.awt.Color(102, 255, 153));
        lblTrainerId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTrainerId.setForeground(new java.awt.Color(0, 0, 0));
        lblTrainerId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrainerId.setText("Trainer Id");
        lblTrainerId.setToolTipText("");
        lblTrainerId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTrainerId.setOpaque(true);

        inputTrainerId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputTrainerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTrainerIdActionPerformed(evt);
            }
        });

        Remove.setBackground(new java.awt.Color(0, 0, 0));
        Remove.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Remove.setForeground(new java.awt.Color(204, 204, 204));
        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTrainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputTrainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTrainerId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        String key = inputTrainerId.getText().strip();
        if(!key.isEmpty()) {
            try {
                admin.removeTrainer(key);
                JOptionPane.showMessageDialog(this, "The Trainer with Id = " + key + " has been deleted");
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(this,"Please enter a Trainer Id to remove.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_RemoveActionPerformed

    private void inputTrainerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTrainerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTrainerIdActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       prevWindow.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Remove;
    private javax.swing.JTextField inputTrainerId;
    // End of variables declaration//GEN-END:variables
}
